[features]
seeds = false
skip-lint = false
[programs.devnet]
mdd_token_transfer = "GdF435gXaeFk3gfRHZbstR3o6g6za5pNdndG79JAzZ5X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
